"""Refresh ``deepvibe_hedge/russell2000.py`` from iShares IWM holdings CSV.

Run once to rebuild the Russell 2000 constituent list::

    PYTHONPATH=src python -m deepvibe_hedge.scripts.refresh_russell2000

The iShares holdings CSV is the authoritative source for IWM membership. We
extract the ticker column, filter to equity asset-class only (drop cash,
derivatives, and currency buckets), normalize Alpaca symbols (convert dots like
``BRK.B`` to dashes ``BRK-B``), and rewrite ``russell2000.py`` in place with a
timestamped provenance block.

After running this script, fetch OHLCV for the (new) Russell tickers::

    PYTHONPATH=src python -m deepvibe_hedge.alpaca_fetcher   # full pipeline

(or use ``--symbols`` with a diff list if you prefer incremental fetches).
"""

from __future__ import annotations

import csv
import io
import re
from datetime import datetime, timezone
from pathlib import Path

import urllib.request

IWM_HOLDINGS_URL = (
    "https://www.ishares.com/us/products/239710/"
    "ishares-russell-2000-etf/1467271812596.ajax"
    "?fileType=csv&fileName=IWM_holdings&dataType=fund"
)

RUSSELL2000_PATH = Path(__file__).resolve().parent.parent / "russell2000.py"


def _fetch_csv_bytes(url: str = IWM_HOLDINGS_URL) -> bytes:
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": (
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/122.0 Safari/537.36"
            ),
            "Accept": "text/csv,*/*;q=0.8",
        },
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def _find_holdings_header(rows: list[list[str]]) -> int:
    """iShares CSVs prepend a provenance/metadata block before the table header.

    Walk rows until we find one whose first cell looks like a ticker header.
    """
    for i, row in enumerate(rows):
        cells = [c.strip().strip('"') for c in row]
        if not cells:
            continue
        first = cells[0].lower()
        if first in ("ticker", "symbol", "issuer ticker"):
            return i
    raise RuntimeError("Could not locate holdings header row in iShares CSV.")


def _normalize_symbol(sym: str) -> str | None:
    """Normalize iShares tickers to Alpaca conventions.

    * Uppercase + strip
    * Skip blanks and non-tickers (cash buckets show up as ``--``, ``USD``, etc.)
    * Convert ``BRK.B`` / ``BF.B`` style dots to Alpaca's ``-`` (``BRK-B``, ``BF-B``)
    * Drop any symbol with characters outside ``[A-Z0-9-]`` (futures, options, FX)
    """
    if not sym:
        return None
    s = sym.strip().strip('"').upper()
    if not s or s in {"--", "USD", "N/A"}:
        return None
    s = s.replace(".", "-").replace("/", "-")
    if not re.fullmatch(r"[A-Z0-9\-]+", s):
        return None
    if len(s) > 6:  # options/futures chains
        return None
    return s


def _parse_holdings(csv_bytes: bytes) -> list[str]:
    text = csv_bytes.decode("utf-8", errors="replace")
    reader = csv.reader(io.StringIO(text))
    rows = list(reader)
    header_idx = _find_holdings_header(rows)
    headers = [c.strip().strip('"').lower() for c in rows[header_idx]]

    try:
        ticker_col = headers.index("ticker")
    except ValueError:
        ticker_col = 0

    asset_col: int | None = None
    for candidate in ("asset class", "asset_class"):
        if candidate in headers:
            asset_col = headers.index(candidate)
            break

    sector_col: int | None = None
    if "sector" in headers:
        sector_col = headers.index("sector")

    tickers: list[str] = []
    for row in rows[header_idx + 1:]:
        if len(row) <= ticker_col:
            continue
        raw_ticker = row[ticker_col]
        sym = _normalize_symbol(raw_ticker)
        if not sym:
            continue
        if asset_col is not None and len(row) > asset_col:
            asset = row[asset_col].strip().strip('"').lower()
            if asset and asset not in ("equity", "stocks", "common stock"):
                continue
        if sector_col is not None and len(row) > sector_col:
            sector = row[sector_col].strip().strip('"').lower()
            if sector in ("cash and/or derivatives", "cash", "currency"):
                continue
        tickers.append(sym)

    seen: list[str] = []
    for t in tickers:
        if t not in seen:
            seen.append(t)
    return seen


def _render_module(tickers: list[str], source_url: str, fetched_at: datetime) -> str:
    lines: list[str] = [
        '"""Russell 2000 constituents (Alpaca symbols). Edit here; ``deepvibe_hedge.config`` imports this tuple.',
        "",
        "Auto-generated by ``deepvibe_hedge.scripts.refresh_russell2000``.",
        f"Source   : {source_url}",
        f"Fetched  : {fetched_at.isoformat()}",
        f"Ticker count: {len(tickers)}",
        "",
        "To refresh::",
        "",
        "    PYTHONPATH=src python -m deepvibe_hedge.scripts.refresh_russell2000",
        '"""',
        "",
        "russell2000: tuple[str, ...] = (",
    ]
    for t in tickers:
        lines.append(f'    "{t}",')
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def refresh(
    *,
    dry_run: bool = False,
    output_path: Path = RUSSELL2000_PATH,
    url: str = IWM_HOLDINGS_URL,
) -> list[str]:
    print(f"Fetching iShares IWM holdings → {url}")
    raw = _fetch_csv_bytes(url)
    print(f"  Downloaded {len(raw):,} bytes")
    tickers = _parse_holdings(raw)
    print(f"  Parsed {len(tickers):,} equity constituents")

    now = datetime.now(timezone.utc)
    module_src = _render_module(tickers, url, now)
    if dry_run:
        print("Dry-run — not writing. First 20 tickers:")
        for t in tickers[:20]:
            print(f"  {t}")
        return tickers

    output_path.write_text(module_src)
    print(f"Wrote {output_path} ({len(tickers):,} tickers, {len(module_src):,} bytes)")
    return tickers


def _parse_argv(argv: list[str]) -> dict[str, object]:
    out: dict[str, object] = {"dry_run": False}
    for a in argv:
        if a in ("--dry-run", "-n"):
            out["dry_run"] = True
    return out


if __name__ == "__main__":
    import sys
    opts = _parse_argv(sys.argv[1:])
    refresh(dry_run=bool(opts["dry_run"]))
